name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: clone build tools
      run: |
        sudo mkdir -p /home/prebuilts
        sudo chown -R $USER:$USER /home/prebuilts
        git clone -b main https://android.googlesource.com/platform/prebuilts/build-tools /home/prebuilts/build-tools
        # sudo apt install -y tree && tree /home/prebuilts/build-tools
    - name: Build with Gradle
      run: |
        ./gradlew build
        /home/prebuilts/build-tools/linux-x86/bin/aconfig create-cache --package com.android.car.dockutil --container system
        ./gradlew :docklib-util:generateDebugFlagCache_com.android.car.dockutil --container system
